---
rocket_chat_service_update_command: systemctl daemon-reload
rocket_chat_service_template:
  src: rocketchat.service.j2
  dest: /etc/systemd/system/rocketchat.service

rocket_chat_mongodb_apt_repo: "deb http://repo.mongodb.org/apt/debian wheezy/mongodb-org/3.0 main"
